### ISSUE TITLE
An annotated type is recognized/highlighted incorrectly, which also botches rename refactoring

### ISSUE THREAD

**Issue by jayesh-bhoot** [ocaml/ocaml-lsp#619] opened 2022-02-11 09:05 UTC
This is best demonstrated with video snippets.

1. VS Code refuses to rename-refactor an annotated type, but allows it if the annotation is removed:

https://user-images.githubusercontent.com/1915507/153563442-79b65682-e479-4a6b-aca9-a295b9d2e4ad.mp4

2. Vim, backed by ocaml-lsp, tries to rename-refactor anyway, and botches it:

https://user-images.githubusercontent.com/1915507/153563640-13c13857-0961-48f5-948a-6dffc04f37b8.mp4

Note that in both the examples, the highlighting seems all kinds of wrong. This is not the case with an unannotated type.

All the binaries come from nix, nixpkgs.
- OCaml: 4.12
- ocaml-lsp: 1.9.0 (built against 4.12? nixpkgs says `ocaml4.12.0-ocaml-lsp-server`)

**Comment by rgrinberg** [comment] 2022-02-13 00:47
paging @voodoos

**Comment by jayesh-bhoot** [comment] 2022-02-15 03:44
I am not using opam, but a Nix env. I open VS Code through that env, so VS Code identifies it as global OCaml. But that's pretty much the only OCaml version on my system.

From what I understand, an opam switch is an isolated environment with its own set of OCaml compiler, build system and libraries. Because of the isolation, various switches can coexist without causing conflicts.

Nix env does the same for me.

> > Did you checked that the selected switch "Global OCaml" matches the switch in your env (selected by opam switch ... and set with eval $(opam env)).

So, in my env, there is no opam (and opam-related `eval`). There is only one OCaml, identified as Global OCaml by VS Code.

As you couldn't reproduce the issue, it seems that this env difference is the problem.

---

Is this a mismatch between the versions of the tools? (I had this issue with ocamlformat and ocamlformat-rpc once.)

```
$ ocaml --version
The OCaml toplevel, version 4.12.0

$ ocamllsp --version
1.9.0
# yours is 1.9.1

$ dune --version
2.9.2

$ ocamlformat --version
0.20.1

$ ocamlformat-rpc --version
0.20.1
```
Let me know if you need more information.

---

> Could you try with the example I used in my tests ?

Still the same:

https://user-images.githubusercontent.com/1915507/153988554-a8a725a7-e643-48d5-b8aa-ea6868f0d617.mp4

**Comment by voodoos** [comment] 2022-02-15 09:18
You setup looks fine. I was able to reproduce. The preprocessing was not correctly configured on my side.

**Comment by voodoos** [comment] 2022-02-15 09:31
I added a test to Merlin's suite: https://github.com/ocaml/merlin/blob/master/tests/test-dirs/occurrences/occ-with-ppx.t

We already have a major rework of `occurrences` (the merlin feature that `ocaml-lsp` uses for highlighting) in the pipes so we probably won't address this before it lands. 

Thanks for the detailed report !

**Comment by jayesh-bhoot** [comment] 2022-02-15 11:22
@voodoos thank you for the quick responses.

Is this an issue with Merlin? I was thinking of configuring a Merlin + Emacs set up for a while now, and this might just be the needed push if Merlin does it right.

**Comment by voodoos** [comment] 2022-02-15 13:00
No the problem is likely to be the same. It might be due to some weirdness in the PPX's output that disturb Merlin.

**Comment by jayesh-bhoot** [comment] 2022-02-15 13:14
Alright.

I will wait for the fix. We can keep this issue open until the fix arrives.

Thank you again.

**Comment by ulugbekna** [comment] 2022-02-16 17:47
It would make more sense to open this issue in merlin repo (https://github.com/ocaml/merlin), so they can keep it in mind, and close this one, since we can't do anything about it here without the merlin fix

**Comment by jayesh-bhoot** [comment] 2022-02-16 18:33
I don't mind doint it if @voodoos doesn't mind either.

**Comment by voodoos** [comment] 2022-02-17 09:06
Feel free to do it, it does makes more sense.

**Comment by jayesh-bhoot** [comment] 2022-02-17 09:19
Does anyone here have a write access to both this and ocaml/merlin repo? If so, then github provides a cleaner approach to transfer an issue: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

> To transfer an open issue to another repository, you must have write access to the repository the issue is in and the repository you're transferring the issue to.

Worth asking before I copy-paste the original post and then hyperlink it to this issue.

**Comment by ulugbekna** [comment] 2022-02-17 09:21
Copy-pasting is fine.

**Comment by jayesh-bhoot** [comment] 2022-02-17 10:05
Issue moved to https://github.com/ocaml/merlin/issues/1438

Feel free to close this issue.

**Closed** 2022-02-17 10:06 UTC
