### ISSUE TITLE
Inconsistent assumptions over interface Parsetree

### ISSUE THREAD

**Issue by sidkshatriya** [ocaml/ocaml-lsp#557] opened 2021-11-25 21:25 UTC
I'm trying to run `make utop` and I keep getting this error. I've used master + Ocaml 4.13, I've tried tag v1.8.3 + OCaml 4.12. I've tried downgrading ocaml-compiler-libs versions... I don't know how to fix this error.

```
Error: Files ocaml-lsp-server/vendor/merlin/src/ocaml/parsing/parsing.cma(Docstrings)
       and /home/abc123/o412/ocaml-lsp/_opam/lib/ocaml/compiler-libs/ocamlcommon.cma(Docstrings)
       make inconsistent assumptions over interface Parsetree
make: *** [Makefile:75: utop] Error 1
```

**Comment by rgrinberg** [comment] 2021-11-26 00:37
The issue is that there are two version of the same toplevel module from compiler-libs

* One provided by merlin itself
* Another from the installed compiler-libs used to create the utop toplevel.

I suppose the correct fix is to wrap compiler-libs in merlin. I'll send a PR to the merlin people, not sure what their response will be though.

**Comment by sidkshatriya** [comment] 2021-11-26 09:42
Thanks for this. Sorry I've still been struggling to get this to work...

- I cherry-picked your above commit over the current git submodule tip in `ocaml-lsp-server/vendor/merlin` (currently 7899193f7288e3db47d802bafb94808da6903b42 ). I was not able to work with your PR _as-is_ because it is based off merlin master...

* This is the cherry-pick with all conflicts resolved (click "Details" to expand) (there also some formatting fuzz -- please ignore that)

<details>

```diff
diff --git a/src/analysis/dune b/src/analysis/dune
index 7000d7f7..b84948a2 100644
--- a/src/analysis/dune
+++ b/src/analysis/dune
@@ -1,15 +1,15 @@
 (library
  (name merlin_analysis)
- (flags -open Merlin_utils)
  (public_name merlin.analysis)
+ (flags -open Ocaml_parsing -open Ocaml_typing -open Merlin_utils)
  (libraries
   config
   merlin_specific
   merlin_extend
   merlin_kernel
   merlin_utils
-  parsing
+  ocaml_parsing
   preprocess
   query_protocol
-  typing
+  ocaml_typing
   utils))
diff --git a/src/extend/dune b/src/extend/dune
index 5b9481d1..ce28472f 100644
--- a/src/extend/dune
+++ b/src/extend/dune
@@ -3,4 +3,5 @@
  (public_name      merlin.extend)
  (wrapped   false)
  (modules   (:standard \ extend_helper))
- (libraries parsing typing unix utils))
+ (flags -open Ocaml_parsing -open Ocaml_typing)
+ (libraries ocaml_parsing ocaml_typing unix utils))
diff --git a/src/frontend/dune b/src/frontend/dune
index 23e84a59..78eb7587 100644
--- a/src/frontend/dune
+++ b/src/frontend/dune
@@ -2,20 +2,20 @@
  (name      query_protocol)
  (public_name merlin.query_protocol)
  (modules   query_protocol)
- (flags -open Merlin_utils)
- (libraries merlin_kernel merlin_utils parsing))
+ (flags -open Merlin_utils -open Ocaml_parsing)
+ (libraries merlin_kernel merlin_utils ocaml_parsing))
 
 (library
  (name      query_commands)
  (public_name      merlin.query_commands)
  (modules   query_commands)
- (flags -open Merlin_utils -open Merlin_analysis)
+ (flags -open Ocaml_parsing -open Ocaml_typing -open Merlin_utils -open Merlin_analysis)
  (libraries
   merlin_utils
   merlin_kernel
   utils
-  parsing
-  typing
+  ocaml_parsing
+  ocaml_typing
   merlin_specific
   config
   merlin_analysis
diff --git a/src/frontend/ocamlmerlin/dune b/src/frontend/ocamlmerlin/dune
index b4f149e3..ad00c9b7 100644
--- a/src/frontend/ocamlmerlin/dune
+++ b/src/frontend/ocamlmerlin/dune
@@ -4,11 +4,11 @@
  (name ocamlmerlin_server)
  (package merlin)
  (public_name ocamlmerlin-server)
- (flags -open Merlin_utils -open Merlin_analysis)
+ (flags -open Ocaml_parsing -open Ocaml_typing -open Merlin_utils -open Merlin_analysis)
  (modules (:standard \ gen_ccflags))
  (libraries config yojson merlin_analysis merlin_kernel
-            merlin_utils os_ipc parsing query_protocol query_commands
-            typing utils))
+            merlin_utils os_ipc ocaml_parsing query_protocol query_commands
+            ocaml_typing utils))
 
 (executable
  (name      gen_ccflags)
diff --git a/src/kernel/dune b/src/kernel/dune
index ce94f38e..47b4ffad 100644
--- a/src/kernel/dune
+++ b/src/kernel/dune
@@ -5,8 +5,8 @@
  (name merlin_kernel)
  (public_name merlin.kernel)
  (wrapped false)
- (flags -open Merlin_utils)
- (libraries config os_ipc parsing preprocess typing utils
+ (flags -open Merlin_utils -open Ocaml_parsing -open Ocaml_typing)
+ (libraries config os_ipc ocaml_parsing preprocess ocaml_typing utils
             merlin_extend merlin_specific merlin_utils merlin_dot_protocol))
 
 (rule
diff --git a/src/ocaml/merlin_specific/dune b/src/ocaml/merlin_specific/dune
index 7eb55287..3969bc00 100644
--- a/src/ocaml/merlin_specific/dune
+++ b/src/ocaml/merlin_specific/dune
@@ -2,5 +2,5 @@
   (name merlin_specific)
   (public_name merlin.specific)
   (wrapped false)
-  (flags -open Merlin_utils)
-  (libraries merlin_utils parsing preprocess typing utils))
+  (flags -open Ocaml_parsing -open Ocaml_typing -open Merlin_utils)
+  (libraries merlin_utils ocaml_parsing preprocess ocaml_typing utils))
diff --git a/src/ocaml/parsing/dune b/src/ocaml/parsing/dune
index 05328ed1..4dcb164e 100644
--- a/src/ocaml/parsing/dune
+++ b/src/ocaml/parsing/dune
@@ -1,10 +1,15 @@
-(rule (copy# ../../extend/extend_helper.ml  extend_helper.ml ))
-(rule (copy# ../../extend/extend_helper.mli extend_helper.mli))
+(rule
+ (copy# ../../extend/extend_helper.ml extend_helper.ml))
+
+(rule
+ (copy# ../../extend/extend_helper.mli extend_helper.mli))
 
 (library
-  (name parsing)
-  (public_name merlin.parsing)
-  (wrapped false)
-  (flags -open Merlin_utils (:standard -w -9))
-  (modules_without_implementation asttypes parsetree)
-  (libraries merlin_utils utils))
+ (name ocaml_parsing)
+ (public_name merlin.parsing)
+ (flags
+  -open
+  Merlin_utils
+  (:standard -w -9))
+ (modules_without_implementation asttypes parsetree)
+ (libraries merlin_utils utils))
diff --git a/src/ocaml/preprocess/dune b/src/ocaml/preprocess/dune
index 0446d6b0..5c28d5f2 100644
--- a/src/ocaml/preprocess/dune
+++ b/src/ocaml/preprocess/dune
@@ -4,8 +4,8 @@
   (name preprocess)
   (public_name merlin.preprocess)
   (wrapped false)
-  (flags -open Merlin_utils)
-  (libraries parsing utils merlin_utils))
+  (flags -open Ocaml_parsing -open Merlin_utils)
+  (libraries ocaml_parsing utils merlin_utils))
 
 (menhir
  (modules parser_raw)
diff --git a/src/ocaml/typing/dune b/src/ocaml/typing/dune
index efb35a4d..557f0202 100644
--- a/src/ocaml/typing/dune
+++ b/src/ocaml/typing/dune
@@ -1,7 +1,11 @@
 (library
-  (name typing)
-  (public_name merlin.typing)
-  (wrapped false)
-  (flags -open Merlin_utils (:standard -w -9))
-  (modules_without_implementation annot outcometree)
-  (libraries merlin_utils parsing utils))
+ (name ocaml_typing)
+ (public_name merlin.typing)
+ (flags
+  -open
+  Ocaml_parsing
+  -open
+  Merlin_utils
+  (:standard -w -9))
+ (modules_without_implementation annot outcometree)
+ (libraries merlin_utils ocaml_parsing utils))
```
</details>



* Then there is a small diff to the ocaml-lsp-server dune file

```diff
diff --git a/ocaml-lsp-server/src/dune b/ocaml-lsp-server/src/dune
index 39e2837..3632cd7 100644
--- a/ocaml-lsp-server/src/dune
+++ b/ocaml-lsp-server/src/dune
@@ -1,5 +1,6 @@
 (library
  (name ocaml_lsp_server)
+ (flags -open Ocaml_parsing -open Ocaml_typing -open Merlin_utils)
  (libraries
   dyn
   xdg
```

* I am able to build successfully i.e. `make all` is successful
* `opam install utop`
* Finally, when I do: `make utop`

```
[...]
File "ocaml-lsp-server/vendor/merlin/src/kernel/merlin_kernel.cma(Pparse)", line 1:
Warning 31 [module-linked-twice]: files ocaml-lsp-server/vendor/merlin/src/kernel/merlin_kernel.cma(Pparse) and /home/sidk/o413/ocaml-lsp/_opam/lib/ocaml/compiler-libs/ocamlcommon.cma(Pparse) both define a module named Pparse
File "_none_", line 1:
Error: Files .utop/.utop.eobjs/byte/dune__exe__Utop.cmo
       and ocaml-lsp-server/vendor/merlin/src/ocaml/utils/utils.cma(Clflags)
       make inconsistent assumptions over interface Clflags
make: *** [Makefile:75: utop] Error 1
```

**Comment by sidkshatriya** [comment] 2021-11-26 11:25
**Ok I have been able to get utop working.** 

Just like we wrapped parsing and typing we need to do another wrapping:

```diff
diff --git a/src/ocaml/utils/dune b/src/ocaml/utils/dune
index 00408517..11e4bf74 100644
--- a/src/ocaml/utils/dune
+++ b/src/ocaml/utils/dune
@@ -1,7 +1,8 @@
 (library
-  (name utils)
-  (public_name merlin.utils)
-  (wrapped false)
-  (libraries config merlin_utils)
-  (flags (-open Merlin_utils))
-  (modules_without_implementation result_compat))
+ (name ocaml_utils)
+ (public_name merlin.utils)
+ (wrapped true)
+ (libraries config merlin_utils)
+ (flags
+  (-open Merlin_utils))
+ (modules_without_implementation result_compat))
```

Then substitute `ocaml_utils` wherever the library `utils` was used and add a flag `-open Ocaml_utils`. 

Then, in `ocaml-lsp-server/src/dune` we have:

```diff
diff --git a/ocaml-lsp-server/src/dune b/ocaml-lsp-server/src/dune
index 39e2837..20fd7d4 100644
--- a/ocaml-lsp-server/src/dune
+++ b/ocaml-lsp-server/src/dune
@@ -1,5 +1,14 @@
 (library
  (name ocaml_lsp_server)
+ (flags
+  -open
+  Ocaml_parsing
+  -open
+  Ocaml_typing
+  -open
+  Merlin_utils
+  -open
+  Ocaml_utils)
  (libraries
   dyn
   xdg
```

**After doing all of this `make utop`** works!

**Comment by rgrinberg** [comment] 2021-11-27 15:42
Thanks. I updated the PR with your fix.

It's quite an embarrassing problem that is generally common in OCaml, the namespacing story is very poor. I rarely use the repl either so I don't often notice things like this.

I'm closing the issue as there's not much more we can do here. If the merlin folks accept the PR, this issue is fixed, if they don't, I don't want to maintain a patch just to make the toplevel work.

**Closed by rgrinberg** 2021-11-27 15:42 UTC
