### ISSUE TITLE
LSP misbehaving after update to new merlin

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#213] opened 2020-07-03 15:26 UTC
Hi, 

The latest ocaml-lsp is misbehaving: cannot find modules and gives "Bad csexp" error on all files on line 2. 

![image](https://user-images.githubusercontent.com/16353531/86481842-0b6e4c80-bd51-11ea-9cc9-b4cb5bbd0e82.png)

This behavior is not present before update to new merlin (b20c342). I looked for when "bad csexp" error would occur; it seems that merlin cannot properly parse `.merlin` file (can't find it?)

Editor: VS code
OS: macOS Catalina
ocaml-lsp version: latest (b4e8c47)

**Comment by rgrinberg** [comment] 2020-07-03 21:39
cc @voodoos

**Comment by voodoos** [comment] 2020-07-03 22:08
The next release of Merlin will pack some important changes: Merlin will start relying on external tools to read its configuration file.

This new version depends on a new binary `dot-merlin-reader`. Because `ocaml-lsp-server` vendors merlin, installing it does not install `dot-merlin-reader` and it should eventually be added as an opam dependency.

It has not been released yet, but you can try to install it yourself:
`opam pin add dot-merlin-reader https://github.com/voodoos/merlin.git#fix-csxep-result` 

I am under the impression that this should solve the issue. I just updated `ocaml-lsp-server` on my side without problem.

**Comment by ulugbekna** [comment] 2020-07-04 08:10
`opam pin add dot-merlin-reader https://github.com/voodoos/merlin.git#fix-csxep-result` indeed fixes the problem.

**Comment by rgrinberg** [comment] 2020-07-05 04:29
Duplicate of #214

**Closed by rgrinberg** 2020-07-05 04:29 UTC
