### ISSUE TITLE
I want more explanations on the lsp folder

### ISSUE THREAD

**Issue by SoilihBenSoilih** [ocaml/ocaml-lsp#372] opened 2021-02-12 14:43 UTC
Hello, 
Can someone please explain me an overview of the architecture of the content on "lsp" folder et how to run an exemple?
What does the import.ml file do too?
Is this folder independant to other?

Thank you a lot !!!

**Comment by rgrinberg** [comment] 2021-03-02 21:30
Duplicate of #238. @SoilihBenSoilih try using the discussions tab for general help. Lets' reserve issues for bug reports and fleshed out feature requests.

**Closed by rgrinberg** 2021-03-02 21:30 UTC
