### ISSUE TITLE
ocaml-lsp reports bogus erros on large files when editor autosaving is enabled

### ISSUE THREAD

**Issue by copy** [ocaml/ocaml-lsp#1003] opened 2023-01-09 19:42 UTC
I can reproduce the following issue on OCaml 4.14 with ocaml-lsp-server 1.13.1 and 1.14.2, and OCaml 5.0 with ocaml-lsp-server pinned to current `#500` (176d387926dfb0a0b2b0196395ad38000395c049).

It's a bit tricky to reproduce, but the following seems to work relatively reliably.

```
% opam source core
Successfully extracted to /tmp/core.v0.15.1
% dune build -w core/src/core.cmxs
```

Make some quick changes in large file with auto-saving enabled. I use the following vimrc:

```
command! AutoWrite autocmd TextChanged,InsertLeave <buffer> try | undojoin | silent! update | catch /^Vim\%((\a\+)\)\=:E790/ | finally | silent! update | endtry

augroup autowrite
    autocmd!
    autocmd Filetype ocaml AutoWrite
augroup END
```

Edit `core/src/command.ml` and repeatedly paste `open Sys` at the top. After a few pastes, lsp reports a bogus syntax error, while the dune watch command doesn't print anything of the sort. 

Here is a recording: https://asciinema.org/a/gQqsK784tKJYwPxtB7wBn6I61
And the lsp logfile: [lsp.log](https://github.com/ocaml/ocaml-lsp/files/10376336/lsp.log)

**Comment by rgrinberg** [comment] 2023-01-10 15:14
Are you sure you need watch mode to reproduce this? If lsp reports a false syntax error, the issue is likely due to document synchronization.

**Comment by copy** [comment] 2023-01-10 15:44
Yeah, I'm pretty sure the issue only happens when watch mode is running.

**Comment by rgrinberg** [comment] 2023-01-10 15:45
What about when you do the following:

1. Get to the state where the server is showing you a false syntax error
2. Save the document - `:w`

Will you still see the syntax error?

**Comment by copy** [comment] 2023-01-10 15:52
Yes, the syntax error is still present after `:w`. The only way to get rid of it is to delete the offending line or restart the lsp.

**Comment by rgrinberg** [comment] 2023-01-10 16:08
Okay, then do you mind trying this PR? https://github.com/ocaml/ocaml-lsp/pull/1004

This sounds like a syncing issue.

**Comment by copy** [comment] 2023-01-10 16:23
Unfortunately, the issue still happens with #1004 applied.

**Comment by rgrinberg** [comment] 2023-01-10 16:25
I'll have a closer look. Thanks for testing.

**Comment by rgrinberg** [comment] 2023-01-10 20:02
I was unable to reproduce the issue on master after a lot of trying. @ulugbekna have you ran into issues like this?

**Comment by rgrinberg** [comment] 2023-01-12 00:25
Fixed by #1004

**Closed by rgrinberg** 2023-01-12 00:25 UTC

**Comment by ulugbekna** [comment] 2023-01-12 00:29
1. You probably meant #1005
2. I can't reproduce the problem with #1005 indeed, but let's also wait for @copy's feedback

**Comment by rgrinberg** [comment] 2023-01-12 00:30
Yes, I meant the other PR. @copy please re-open if you can still repro the bug.

**Comment by copy** [comment] 2023-01-13 15:52
I can confirm that this is fixed, cheers!
