### ISSUE TITLE
go-to definition doesn't work with files that exists within _build

### ISSUE THREAD

**Issue by mimoo** [ocaml/ocaml-lsp#544] opened 2021-10-21 19:15 UTC
As part of my codebase I have some `.ml` files that are automatically generated (via dune rules) and as such are only present within the `_build` directory. When I try to go to the definition, I would expect my IDE to open the generated files that are in that _build directory but it doesn't and can't find the definition.

(I can provide instructions on how to repro if that's helpful)

**Comment by ulugbekna** [comment] 2021-11-08 16:48
a duplicate of #470

**Closed by ulugbekna** 2021-11-08 16:48 UTC
