### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jfeser** [ocaml/ocaml-lsp#107] opened 2020-02-26 23:53 UTC
ocaml-lsp's memory use grows when I modify a file that it's watching. I've seen it use up to 20Gb of memory. After bisecting, it seems that the bug was introduced by 8a27349f6bc5e1d2483f574ca416f726ed1c9b07. Unfortunately, it's a huge commit so I don't see an obvious culprit.

This is on macos 10.15.3, ocaml 4.08.1.

**Comment by rgrinberg** [comment] 2020-02-27 00:26
Interesting. Can you confirm that there is no leak prior to that commit?

**Comment by jfeser** [comment] 2020-02-27 00:49
Yep. Before that commit, the server allocates memory as the file is modified, but it periodically frees it. After, I don't see total memory use go down.

**Comment by Kakadu** [comment] 2020-02-29 13:00
These leaks are annoying. Please, do something!

**Comment by rgrinberg** [comment] 2020-02-29 13:02
Right away boss, we're working around the clock 😂 😂 😂

**Comment by giltho** [comment] 2020-02-29 13:03
@Kakadu if you want to contribute to fix these annoying leaks, I believe PRs to the project are most welcome :)

**Comment by giltho** [comment] 2020-02-29 13:04
I have been looking a tiny bit, and the only possible suspect I found is the use of `Stdune.Table` (and `Stdune.String.Table`)  instead of `hashtbl`s. However, given the implementation, I cannot see how that could be the cause

**Comment by rgrinberg** [comment] 2020-02-29 13:08
I've tried measuring what is leaking using spacetime before & after the commit but wasn't able to observe anything interesting either. @jfeser perhaps you can use spacetime to give us some snapshots of how the heap is evolving?

**Comment by rgrinberg** [comment] 2020-02-29 13:10
> I have been looking a tiny bit, and the only possible suspect I found is the use of Stdune.Table (and Stdune.String.Table) instead of hashtbls. However, given the implementation, I cannot see how that could be the cause

Indeed the commit seems innocuous.

**Comment by ulugbekna** [comment] 2020-02-29 13:28
I noticed memory leaks with ocamlmerlin-server a long time ago ocaml/merlin#878; don't know if related or helpful.

**Comment by rgrinberg** [comment] 2020-02-29 13:32
> I noticed memory leaks with ocamlmerlin-server a long time ago ocaml/merlin#878; don't know if related or helpful.

This is my suspicion as well. ocamllsp makes the problem worse because it introduces additional caching of the merlin state. However, this caching was present way before the commit @jfeser pointed to was introduced.

**Comment by Kakadu** [comment] 2020-02-29 14:03
> @Kakadu if you want to contribute to fix these annoying leaks, I believe PRs to the project are most welcome :)

It  seems that not this time. 8GB of RAM is not enough even to compile dune with `ocaml-4.07+spacetime`

**Comment by giltho** [comment] 2020-02-29 14:20
Missclick, not used to android app yet :/
I'm gonna try to reproduce this, is there a particular kind of files that do this or do you observe the leak on every files ?

**Comment by Kakadu** [comment] 2020-02-29 14:46
I have two projects working on. Both are leaking.

**Comment by rgrinberg** [comment] 2020-02-29 17:56
How many files do you have open? If you close files, you should observe a reduction in memory used.

@giltho what might be useful here are some commands that dump the sizes of the various tables we store in memory. The document store table and the cmi table are good candidates for things that consume lots of memory

**Comment by giltho** [comment] 2020-02-29 18:11
I'll try to write a command that print tables.
In the meanitme, @Kakadu and @jfeser , what editor are you using ? Is there a way you could extract the lsp logs of an execution that leaks ?

**Comment by hcarty** [comment] 2020-02-29 18:12
I can do more concrete tests on Monday, but I usually see 3-5 gigabytes of memory used by the ocamllsp process, also macos and OCaml 4.08.1. When it gets much higher that that I've generally killed the ocamllsp process and let the editor/plugin restart it. The peak I've seen so far is 8 gigabytes. 

Running under the labs vscode plugin if that makes a difference, and 5-8 files open but somewhat frequently moving between other files and closing them. Not sure if the combo of vscode and ocamllsp keeps some of those closed files alive.

**Comment by giltho** [comment] 2020-02-29 19:01
On vscode, if you're using merlin-language-server, it is possible to extract the lsp logs using the following conf:
```json
{
  "merlin-language-server.trace.server": "verbose"
}
```
Then, copy paste everything from the "Merlin Language Server" output into a file.
If anyone with memory leaks could extract a log file and send it here, we could understand what kind of execution leads to the leaks :)

I'm trying to reproduce on my side but my projects don't seem to be causing leaks.

**Comment by jfeser** [comment] 2020-02-29 19:40
I'm using emacs with lsp-mode. I see leaks with only one file open. The increase happens whenever the file is edited. One guess I have is that it might be related to ppx generating files that get cached and never released.

I'll see if I can get some logs and post them here. 

I've tried spacetime; I can get it to produce a trace, but the trace viewer crashes when loading.

**Comment by giltho** [comment] 2020-03-01 17:43
I wrote a little command that lets you print table sizes.
It prints the length of:
 - the length of the Document_store table
 - the length of the Cmi_cache table
The code is a bit dirty, I modified the Document_store code in the server and the File_cache code in merlin to add some `get_size` functions, and I'm showing it in a `ShowMessage`.
What it shows mostly is that these tables seem to never get emptied.
I'm mostly worried about the Document. It is never emptied, and every time we type a character, it gets a new copy of the file.
I think there is also a way of flushing the cmi cache from times to times, but I would say the document table is what's wrong
A simple way could be to periodically clean thes table ? Like every 20 requests or something, and only keep the last ~30 versions of a file. Also, adding a DidCloseTextDocument handler to remove the files that were closed from the store ?

**Comment by rgrinberg** [comment] 2020-03-01 18:11
Yes, we never clear the cmi/cmt caches. I believe merlin simply flushes the cache every fixed period.

For the document table, why not just clear the entries whenever the user closes a file? As far as I know, LSP should be telling us when this happens.

**Comment by giltho** [comment] 2020-03-01 18:44
I'll start by implementing the `DidCloseTextDocument`  callback.
Also, what's the workflow for submitting PRs that include changes in the merlin submodule ?

However, I think there's something else wrong. The memory usage sometimes jumps a lot when entering a few characters in a file that's about 12KB. 

![lspmemory](https://user-images.githubusercontent.com/8451179/75631612-466a4300-5bec-11ea-851b-8febb07c5ad7.gif)

The first line of my htop is the LSP, look at the RES column

**Closed** 2020-03-02 14:50 UTC

**Comment by giltho** [comment] 2020-03-02 14:52
Thanks for reporting @jfeser and @Kakadu, please tell us if you still notice the leak hasn't gone, but it should be. @jfeser, the leak seemed indeed to have been introduced by stdune in the commit you mentioned :)

**Comment by tzoz** [comment] 2020-06-23 15:49
Sorry to resurrect this, but I've been having this issue lately. After working for a while the memory usage just explodes. I have 12GB of RAM on this machine and I've seen it get close to using all of it. So far my only solution is to just kill the ocamllsp process.

**Comment by giltho** [comment] 2020-06-23 15:55
Hi @tzoz :)
Which commit are you using ?
Have you noticed a change that caused a new leak recently or has this "always" happened for you ?

**Comment by tzoz** [comment] 2020-06-23 17:47
I've been staying synced with the latest version through opam, as shown in the readme:
`opam pin add ocaml-lsp-server https://github.com/ocaml/ocaml-lsp.git`
I would estimate that this has been happening for the past few weeks at least, but I couldn't give you an exact number.

For my setup, if this helps, I'm using the `lsp` emacs package with the `company-lsp` backend. Additionally, would `merlin` interact with `ocamllsp` in some way that causes this problem?

**Comment by rgrinberg** [comment] 2020-06-26 02:38
> I would estimate that this has been happening for the past few weeks at least, but I couldn't give you an exact number.

It would be extremely helpful of you could try to pin point the exact commit where this leak was introduced. Otherwise, it's not likely that we'll be able to resolve this.

**Comment by Kakadu** [comment] 2020-07-01 09:31
Two questions:
1) Is it possible to add special command which will say how much memory is allocated by various parts of merlin data structures?
2) Is it possible to prepare a test that will do a lot of commands and reproduce this big memory consumption?

**Comment by giltho** [comment] 2020-07-01 15:47
@Kakadu For 1, I had written a command to do this at some point and I could dig it up. However, I only managed to show the number of elements in the Document table / Cmi table. What's the best way in OCaml to show the actual size in memory of a data structure ? Like, if instead of the number of elements I want to see the actual size it has in memory ?

**Comment by Kakadu** [comment] 2020-07-01 16:06
@giltho I googled a bit and it seems that we should start  trying from `Obj.reachable_words`....
