### ISSUE TITLE
Module aliases do not get completion

### ISSUE THREAD

**Issue by Lupus** [ocaml/ocaml-lsp#130] opened 2020-03-15 18:19 UTC
```
module ZZZ = Base;
ZZZ.<tab>
```
Nothing is being shown.

`Base.<tab>` works as expected. Not sure if it's related to vscode extension or ocaml-lsp itself.

**Comment by zth** [comment] 2020-04-04 20:26
Potentially related, for me records defined inside a module but used outside of it don't get autocomplete. Maybe the same underlying issue?

**Comment by giltho** [comment] 2020-04-21 13:25
This might be a merlin issue though

**Comment by giltho** [comment] 2020-07-17 13:04
![image](https://user-images.githubusercontent.com/8451179/87788586-e17f5480-c83d-11ea-9062-5541cdd45581.png)
![image](https://user-images.githubusercontent.com/8451179/87789006-9ca7ed80-c83e-11ea-813c-f9b0d29183d2.png)

I can't reproduce either of these bugs :/
I'm using OCaml 4.10 here, so there might have been some improvements on merlin since then. I'm closing this issue but please do tell me if you manage to reproduce :)

**Closed by giltho** 2020-07-17 13:04 UTC
Labels: bug

**Comment by ulugbekna** [comment] 2020-07-17 15:12
This is a merlin issue [see](https://github.com/ocaml/merlin/issues/1135)

**Comment by giltho** [comment] 2020-07-17 15:25
Thanks for clarification :)
But in this case, `ZZZ.` is not correct ocaml is it ?

**Comment by ulugbekna** [comment] 2020-07-17 15:29
Why so? If you have capitalization in mind, I don't think that's a problem

![image](https://user-images.githubusercontent.com/16353531/87803619-09c57e00-c853-11ea-900f-8c6f4e60d2a3.png)

**Comment by giltho** [comment] 2020-07-17 15:36
Hmm, I'm partially wrong
For this to be correct you need `;;` after `List`

For example, this is incorrect :
```ocaml
module Test = struct let main () = () end
Test.main ()
```
but this isn't
```ocaml
module Test = struct let main () = () end;;;
Test.main ()
```

But I've never seen `;;` used in ocaml program in production outside of scripts.
Anyway, in this case, merlin still doesn't produce the `main` after `Test.` so it is a bug indeed

**Comment by ulugbekna** [comment] 2020-07-17 15:41
Jane Street heavily use `;;` in their code (for better errors afaik), e.g., 

![image](https://user-images.githubusercontent.com/16353531/87804823-b3593f00-c854-11ea-93c1-1fe895200967.png)

**Comment by giltho** [comment] 2020-07-17 15:44
Ah interesting, thank ! Happy to learn anything 😊
