### ISSUE TITLE
A kind of "hello world" 

### ISSUE THREAD

**Issue by SoilihBenSoilih** [ocaml/ocaml-lsp#370] opened 2021-02-08 15:08 UTC
I want to develop an lsp server implemented in ocaml for an programming language in development. I have seen your project, but i don't understand what to write and where to do what, what file is for what...etc So I want a kind of hello word project to understand where to write what and then, keep going by myself. Or more explanation in the structure of the project and the matter of the files.

Thank you a lot !!!

**Comment by tmattio** [comment] 2021-02-09 14:39
Hi @SoilihBenSoilih. The only piece that is specific to OCaml is the `ocaml-lsp-server` project. The other projects are protocol implementations and should be general to every LSP:

- jsonrpc holds the Jsonrpc protocol implemenation
- lsp hods the LSP protocol implementation

If you want to reuse pieces of this repo for your project, I would suggest the following:

- Fork the whole project
- Strip out everything in `ocaml-lsp-server` except `ocaml_lsp_server.ml`
- Refactor `ocaml_lsp_server.ml` to replace the bits specific to ocaml lsp by your own logic (e.g. the request handlers in `on_request`, or the code actions in `code_action`).

I'll note that the libraries used are a bit unconventional (i.e. `Fiber` for the concurrency) and you probably won't be familiar with them unless you've worked in Dune. Unfortunately, documentation these libraries is not a priority, so I hope the interfaces and the usage throughout the repo will be enough for you to get productive with them.

**Comment by c-cube** [comment] 2021-02-09 15:42
For what it's worth, I've been working on using `lsp` in a project of mine (another language), and @Gbury and I have discussed providing a higher-level abstraction on top of `lsp`. It's [here](https://github.com/c-cube/linol) (very WIP).

**Comment by tmattio** [comment] 2021-02-09 15:52
This makes me realized that in fact `jsonrpc` and `lsp` are published on Opam, so you don't have to fork the whole repo to use them.

> @Gbury and I have discussed providing a higher-level abstraction on top of lsp

Really good to know, thank's for the repo, I'll check it out!

**Comment by SoilihBenSoilih** [comment] 2021-02-10 01:59
Thank you a lot for your explanations !

**Comment by SoilihBenSoilih** [comment] 2021-02-15 14:47
Excuse me guys, how to test the content of the **LSP folder** in vscode ?
i have compiled all with the command `dune build` and all the errors have disappeared. 
And now how to test with a file with witch extension in order to see how it works? 
Thank you a lot !

**Comment by Gbury** [comment] 2021-02-21 21:52
Small update on the higher-level abstraction over `lsp` that @c-cube  mentioned above: you can now find an example/base template to start with it here : https://github.com/c-cube/linol/tree/master/example/template , the example contains both a `main.ml` to show usage of the lib, as well as the `dune` file needed to compile it.

**Comment by rgrinberg** [comment] 2021-03-02 21:26
This is a duplicate of #238

**Closed by rgrinberg** 2021-03-02 21:26 UTC
