### ISSUE TITLE
feature request: go to implementations

### ISSUE THREAD

**Issue by mimoo** [ocaml/ocaml-lsp#463] opened 2021-06-10 01:11 UTC
so with ocaml-lsp-server and vscode, if I click on a module that was created by a functor it'll go to the definition of that functor but not the actual use of that functor to create the module. Any idea how I can get the latter?

**Comment by ulugbekna** [comment] 2021-06-10 12:05
Duplicate of https://github.com/ocaml/merlin/issues/1199, fixed by https://github.com/ocaml/merlin/pull/1329. The fix is already present on master branch of this repo. (The master branch has also some other new features, if you want to try them out ;))

**Comment by mimoo** [comment] 2021-07-13 18:40
btw you linked to the merlin repo, but are you referring to the master branch of ocaml-lsp?

**Comment by ulugbekna** [comment] 2021-07-13 18:56
Yes, the fix is on ocaml-lsp's master (and the latest release I think (?))

Merlin is ocaml-lsp's backend, which is responsible for completion, go-to's, etc. So this issue needed a fix in merlin.

**Closed** 2021-07-13 18:56 UTC
