### ISSUE TITLE
Uncaught exception on Windows

### ISSUE THREAD

**Issue by kkirstein** [ocaml/ocaml-lsp#395] opened 2021-03-31 09:27 UTC
Using VSCode, OCaml-Platform & ocaml-lsp-server, I recently observe regular crashes of `ocamllsp` on Windows:
```
ocamllsp: internal error, uncaught exception:
          Fiber_unix__Scheduler.Abort(_)
          Raised at Fiber_unix__Scheduler.run in file "fiber-unix/src/scheduler.ml", line 390, characters 15-30
          Called from Dune__exe__Ocaml_lsp_server.start in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 892, characters 2-299
          Called from Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 155, characters 8-12
          Re-raised at Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 161, characters 4-19
          Called from Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 187, characters 10-34
          Re-raised at Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 193, characters 6-21
          Called from Cmdliner_term.app.(fun) in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
          Called from Cmdliner.Term.run in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner.ml", line 117, characters 32-39
```
My setup is
Windows 10, OCaml for Windows 4.12.0 (cygwin environment, mingw toolchain)
`vscode 1.54.3`
`ocaml-platform 1.8.2`
`merlin 4.1-412`
`ocaml-lsp-server pinned to github.com/ocaml/ocaml-lsp.git` (I am using this, to get a fix for another [issue](https://github.com/ocamllabs/vscode-ocaml-platform/issues/532))

Maybe this is related to the recent update of the `Fiber` module?

**Comment by kkirstein** [comment] 2021-03-31 09:50
Same issue also shows up, when using WSL2 (Ubuntu 20.04) on Windows 10 and remotely connecting with vscode.

**Comment by rgrinberg** [comment] 2021-04-01 03:54
I plan on getting rid of lsp's own fiber scheduler and replace it with dune's. I just need to add a few more features to it first.

**Comment by kkirstein** [comment] 2021-04-01 08:03
Yes, I can check the commits to find the critical one, but it might take some days (Easter!). First, I can tell that https://github.com/ocaml/ocaml-lsp/commit/bb438db2f0a5c24ecc518e51bf907f9edb8d80bd (`tag 1.5.0`) is still working.

**Comment by ulugbekna** [comment] 2021-04-03 14:24
I observed those errors on macos as well. I tried to bisect, and it seems to start after the update to the latest fiber (1b30c0b51f169fca083f248a4751522f6fe2fbc2).

With slightly changed `Scheduler.run` to get what's inside `Abort(_)` exception, I have this 

```
ocamllsp: internal error, uncaught exception:
          Abort (Code_error ("Fiber.Stream.Out: already writing", {}))
          Raised at Stdune__Code_error.raise in file "vendor/stdune-unstable/code_error.ml", line 9, characters 30-62
          Called from Fiber.Stream.Out.lock in file "vendor/fiber/fiber.ml", line 766, characters 24-79
          Called from Fiber.Stream.Out.write in file "vendor/fiber/fiber.ml", line 786, characters 6-12
          Called from Fiber.Execution_context.safe_run_k in file "vendor/fiber/fiber.ml", line 118, characters 8-11
          Re-raised at Stdune__Exn.raise_with_backtrace in file "vendor/stdune-unstable/exn.ml", line 36, characters 27-56
          Called from Stdlib__queue.iter.iter in file "queue.ml", line 121, characters 6-15
          Called from Fiber.Execution_context.apply in file "vendor/fiber/fiber.ml", line 196, characters 9-14
          Re-raised at Stdune__Exn.raise_with_backtrace in file "vendor/stdune-unstable/exn.ml", line 36, characters 27-56
          Called from Fiber.Execution_context.apply in file "vendor/fiber/fiber.ml", line 197, characters 13-30
          Called from Fiber.run.(fun).loop in file "vendor/fiber/fiber.ml", line 889, characters 10-57
          Called from Stdune__Exn.protectx in file "vendor/stdune-unstable/exn.ml", line 12, characters 8-11
          Re-raised at Stdune__Exn.protectx in file "vendor/stdune-unstable/exn.ml", line 18, characters 4-11
          Called from Fiber_unix__Scheduler.run_result in file "fiber-unix/src/scheduler.ml", line 377, characters 10-27
          Re-raised at Stdune__Exn.raise_with_backtrace in file "vendor/stdune-unstable/exn.ml", line 36, characters 27-56
          Called from Dune__exe__Ocaml_lsp_server.start in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 895, characters 2-299
          Called from Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 155, characters 8-12
          Re-raised at Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 161, characters 4-19
          Called from Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 187, characters 10-34
          Re-raised at Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 193, characters 6-21
          Called from Cmdliner_term.app.(fun) in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
          Called from Cmdliner.Term.run in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner.ml", line 117, characters 32-39
```

### how to reproduce

I can reproduce quite easily by replacing `_` in `ocaml_lsp_server.ml:851` with `{}`. 

But something weird is that even when I restart the server, it can fail immediately -- so I can't restart the server in some cases. 


Uploading Screen Recording 2021-04-03 at 5.46.14 PM.mov…




------

I also observed that at (maybe even in commits before) updating to the latest stdune (d72f054ba72c4fbfae17d530865f8fcb399884e6), I have quite many failing requests, which didn't seem to be the case before (1.4.0 for example)

```

[Trace - 5:04:22 PM] Sending request 'textDocument/hover - (994)'.
[Trace - 5:04:22 PM] Received response 'textDocument/hover - (994)' in 3ms. Request failed: uncaught exception (-32603).
[Error - 5:04:22 PM] Request textDocument/hover failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
[Trace - 5:04:23 PM] Sending request 'textDocument/hover - (995)'.
[Trace - 5:04:23 PM] Received response 'textDocument/hover - (995)' in 5ms. Request failed: uncaught exception (-32603).
[Error - 5:04:23 PM] Request textDocument/hover failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
[Trace - 5:04:23 PM] Sending request 'textDocument/hover - (996)'.
[Trace - 5:04:23 PM] Received response 'textDocument/hover - (996)' in 4ms. Request failed: uncaught exception (-32603).
[Error - 5:04:23 PM] Request textDocument/hover failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
[Trace - 5:04:24 PM] Sending request 'textDocument/documentHighlight - (997)'.
[Trace - 5:04:24 PM] Received response 'textDocument/documentHighlight - (997)' in 3ms.
[Trace - 5:04:24 PM] Sending request 'textDocument/hover - (998)'.
[Trace - 5:04:24 PM] Received response 'textDocument/hover - (998)' in 4ms. Request failed: uncaught exception (-32603).
[Error - 5:04:24 PM] Request textDocument/hover failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
[Trace - 5:04:24 PM] Sending request 'textDocument/codeAction - (999)'.
[Trace - 5:04:24 PM] Received response 'textDocument/codeAction - (999)' in 1ms.
[Trace - 5:04:24 PM] Sending request 'textDocument/hover - (1000)'.
[Trace - 5:04:24 PM] Received response 'textDocument/hover - (1000)' in 3ms. Request failed: uncaught exception (-32603).
[Error - 5:04:24 PM] Request textDocument/hover failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
[Trace - 5:04:25 PM] Sending request 'textDocument/hover - (1001)'.
[Trace - 5:04:25 PM] Received response 'textDocument/hover - (1001)' in 3ms. Request failed: uncaught exception (-32603).
[Error - 5:04:25 PM] Request textDocument/hover failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
```

**Comment by rgrinberg** [comment] 2021-04-03 22:48
Thanks for investigating, I think I understand what the issue is.

> I can reproduce quite easily by replacing _ in ocaml_lsp_server.ml:851 with {}.

Could you paste a patch (on top of master) for this?  I don't see where we can insert `{}`

**Comment by ulugbekna** [comment] 2021-04-06 13:42
@kkirstein could you check if the issue is resolved by installing ocaml-lsp from the master?

**Comment by kkirstein** [comment] 2021-04-06 15:16
Looks good so far: lsp-server has been running for about 1 hour now without crash. Also, I did some manual restarts of the lsp-server within vscode without problems. Platform: `ocaml-for-windows (Win10, cygwin, mingw)`, `vscode 1.55.0`, `ocaml-platform 1.8.2` & `ocaml-lsp pinned to github master`.
Test with remote access to `WSL2` are pending...

**Comment by kkirstein** [comment] 2021-04-07 07:33
There are also no issues for remote access to `WSL2`.
@ulugbekna I could not observe the described failing requests. Maybe I "stepped over" the causing commits.

To be honest, I did not really get the root cause for the crashes described above, but anyway, thank you for the fix. If there are no objections, I would close the issue.

**Comment by ulugbekna** [comment] 2021-04-07 07:34
Thank you for testing out the fix!

**Closed by ulugbekna** 2021-04-07 07:34 UTC
