### ISSUE TITLE
Using kate editor : Equal sign in let  returns as tip "test equality" what is the wrong info

### ISSUE THREAD

**Issue by devosalain** [ocaml/ocaml-lsp#564] opened 2021-12-05 22:45 UTC
let a=1 
Hoovering over = returns as info "test for equality.".
Pressing "ctrl+space" returns as info 'a->'a->bool , which is the same as "test for equality, but wrong.
The correct answer is in this case is : ""give a name to value""

The same issue is seen with a different editor,
https://github.com/ocamllabs/vscode-ocaml-platform/issues/654

Versions used:
O.S. : FreeBSD v 13.0-RELEASE-p5
Ocaml compiler : v 4.13.1+options
ocaml-lsp-server : v 1.9.1
kate editor : v 21.08.1

If there is a helping test i can do by e.g. sending a manual request to the lsp-server on my pc, feel free to let me know.

**Comment by jfeser** [comment] 2023-07-02 23:45
Closing, because I think the issue is fixed.

If not, please feel free to reopen!

**Closed by jfeser** 2023-07-02 23:45 UTC
Labels: bug, merlin

**Comment by jboillot** [comment] 2024-04-11 16:01
Hello, this is happening again with (at least) ocamllsp v1.17.0. Here are the logs:
```
[Trace - 5:53:18 PM] Sending request 'textDocument/hover - (45)'.
Params: {
    "textDocument": {
        "uri": "file:///redacted.ml"
    },
    "position": {
        "line": 168,
        "character": 5
    }
}


[Trace - 5:53:19 PM] Received response 'textDocument/hover - (45)' in 567ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\npack_configuration\n```\n---\n`e1 = e2` tests for structural equality of `e1` and `e2`. Mutable structures (e.g. references and arrays) are equal if and only if their current contents are structurally equal, even if the two mutable objects are not the same physical object. Equality between functional values raises `Invalid_argument`. Equality between cyclic data structures may not terminate. Left-associative operator, see `Ocaml_operators` for more information."
    },
    "range": {
        "end": {
            "character": 5,
            "line": 168
        },
        "start": {
            "character": 4,
            "line": 168
        }
    }
}
```

Moreover, when defining a module type with `module type M = sig end` I get the same issue:
```
[Trace - 5:58:10 PM] Sending request 'textDocument/hover - (235)'.
Params: {
    "textDocument": {
        "uri": "file:///redacted.ml"
    },
    "position": {
        "line": 13,
        "character": 15
    }
}


[Trace - 5:58:11 PM] Received response 'textDocument/hover - (236)' in 677ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\nsig end\n```\n---\n`e1 = e2` tests for structural equality of `e1` and `e2`. Mutable structures (e.g. references and arrays) are equal if and only if their current contents are structurally equal, even if the two mutable objects are not the same physical object. Equality between functional values raises `Invalid_argument`. Equality between cyclic data structures may not terminate. Left-associative operator, see `Ocaml_operators` for more information."
    },
    "range": {
        "end": {
            "character": 23,
            "line": 13
        },
        "start": {
            "character": 0,
            "line": 13
        }
    }
}
```

Module declaration works as expected, expect when it is a functor. With this code `module Make(M:sig end) = struct end` I get:
```
[Trace - 5:59:50 PM] Sending request 'textDocument/hover - (252)'.
Params: {
    "textDocument": {
        "uri": "file:///redacted.ml"
    },
    "position": {
        "line": 15,
        "character": 23
    }
}


[Trace - 5:59:51 PM] Received response 'textDocument/hover - (252)' in 522ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```ocaml\n'a -> 'a -> bool\n```"
    },
    "range": {
        "end": {
            "character": 24,
            "line": 15
        },
        "start": {
            "character": 23,
            "line": 15
        }
    }
}
```
