### ISSUE TITLE
An exemple of a simple ocaml lsp server with the initial connection request 

### ISSUE THREAD

**Issue by SoilihBenSoilih** [ocaml/ocaml-lsp#376] opened 2021-02-24 03:30 UTC
Hello,

I hope you are well !
I have a project in which I need to write an lsp server in ocaml for a developing language.
So I did a lot of research on this but I'm having a bit of a hard time getting through it.

The Microsoft tutorial https://microsoft.github.io/language-server-protocol/specification speaks sometimes on the server side, sometimes on the client side, sometimes JSON RPC through which requests and notifications must pass between the client and the server, and all of that mixed up, plus typeScript and not ocaml, what i want to use as a language confuses me a bit, i feel like i don't understand anything.

So I turned to code. I saw a lot of code like the one from https://github.com/facebook/flow/tree/master/src/lsp, the one from https://github.com/ocaml/ocaml-lsp but I don't understand really the code, there are a lot of files with a lot of lines, i don't know what does what.
Can you show me an example of how to initiate connection with the first initiate request, send notification in ocaml. I think a little example will help me do the rest.

Thank you very much !

**Comment by mnxn** [comment] 2021-02-24 04:06
I don't know of any simple examples for the lsp library, but the suggestions in your [other issue](https://github.com/ocaml/ocaml-lsp/issues/370) are a good place to start understanding it.

In particular, if you want to see code that interacts with the lsp library, you can focus on the `ocaml_lsp_server.ml` file: https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server/src/ocaml_lsp_server.ml 

For handling requests/notifications, take a look at the `ocaml_on_request` and `on_notification` functions:

https://github.com/ocaml/ocaml-lsp/blob/5df0ce22ce1f24f0ed187cd96c17713c181b0e20/ocaml-lsp-server/src/ocaml_lsp_server.ml#L621

https://github.com/ocaml/ocaml-lsp/blob/5df0ce22ce1f24f0ed187cd96c17713c181b0e20/ocaml-lsp-server/src/ocaml_lsp_server.ml#L798

>  how to initiate connection with the first initiate request

The language server is started and initialized by the language server client (plugins for VSCode, Emacs, Vim, etc).

Initialization is handled by the `Client_request.Initialize` request and `on_initialize` function:
https://github.com/ocaml/ocaml-lsp/blob/5df0ce22ce1f24f0ed187cd96c17713c181b0e20/ocaml-lsp-server/src/ocaml_lsp_server.ml#L148

> send notification in ocaml.

See `send_diagnostics` for an example of sending a notification:
https://github.com/ocaml/ocaml-lsp/blob/5df0ce22ce1f24f0ed187cd96c17713c181b0e20/ocaml-lsp-server/src/ocaml_lsp_server.ml#L72

**Comment by Gbury** [comment] 2021-02-24 10:01
To help with using the `ocaml-lsp` library in order to create lsp servers, @c-cube developped a thin wrapper around the `lsp` library called `linol`. You can find its code there : https://github.com/c-cube/linol
To help people use `linol`, I wrote a small example that can be used as a template for new projects that wish to easily create a server using `linol`, you can find the ml code here :
https://github.com/c-cube/linol/blob/master/example/template/main.ml

**Comment by SoilihBenSoilih** [comment] 2021-02-24 11:52
Thank you all !!!
I have and additionnal question @mnxn. 
Do I have to fork all the project and modify what i want or i can start from a blank project and initialize the server like you showed above? 
If I can start with a blank project after have run `opam install ocaml-lsp-server` of course, how can I use `open import` without and import file ?

**Comment by mnxn** [comment] 2021-02-24 16:52
Forking is unnecessary. You can start from a blank project.

> If I can start with a blank project after have run `opam install ocaml-lsp-server` of course, how can I use open import without and import file ?

`ocaml-lsp-server` is the implementation of a language server for OCaml projects. For your own language, you only need to install [`lsp`](https://opam.ocaml.org/packages/lsp/) (`opam install lsp`).

You don't need an `Import` module. It's just something we use to explicitly list modules we're using. You can just qualify each module name with `Lsp` (e.g. `Lsp.Client_request` or `Lsp.Types.Hover`) or open the lsp modules in your code with `open Lsp` and `open Lsp.Types`.

I do recommend you try the Linol project that @Gbury linked. It looks like it simplifies a lot of boilerplate and would be easier to start with.

**Comment by SoilihBenSoilih** [comment] 2021-02-26 14:01
Hello.

it's much clearer now.

Thank you a lot !

Le mer. 24 févr. 2021 à 09:53, Max Lantas <notifications@github.com> a
écrit :

**Comment by rgrinberg** [comment] 2021-03-02 21:29
Duplicate of #238

**Closed by rgrinberg** 2021-03-02 21:29 UTC
