### ISSUE TITLE
textDocument/formatting is returning unformatted text for certain projects, not others

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [ocaml/ocaml-lsp#390] opened 2021-03-21 15:26 UTC
I am using the `ocamllabs.ocaml-platform` extension in VSCode. I have one project ([published here](https://github.com/FinleyMcIlwaine/bril-ocaml)) where the formatting works just fine with my workflow:

![Formatting correctly](https://i.imgur.com/4qEbVEX.gif)

The above is just me formatting a test file within that project. In my other projects, however, nothing is formatting and the language server is simply returning the unformatted text upon request. I have a minimal example [published here](https://github.com/FinleyMcIlwaine/test-fmt). Below is a GIF of attempting to format the file that shows the language server output:

![Formatting not working](https://i.imgur.com/EcjAVsm.gif)

As you can see, the returned `newText` is just the exact same as the unformatted file above. Both of these examples are using the `janestreet` profile and manually running `ocamlformat test.ml` returns the newlines between the type constructors as expected.

Both projects have `.ocamlformat` files at the root, are using `ocamllsp` 1.4.1 and `ocamlformat` 0.17.0 and both are running out of the same switch. I'm on macOS Big Sur 11.2.1 using `ocamllabs.ocaml-platform` extension version 1.8.1. I've run out of ideas for debugging this ([here's my thread on the OCaml forums](https://discuss.ocaml.org/t/vscode-formatting-works-in-one-project-does-not-work-in-another/7501)), so any other ideas or pointers would be very much appreciated!

People on the forum have noted that they can't reproduce this with similar versions, so I have a feeling it's something wrong with my language server installation, but I can't figure it out.

**Comment by FinleyMcIlwaine** [comment] 2021-04-01 07:25
Adding some more to this issue. The project that correctly formats has multiple modules and they all load just fine and no issues are reported as long as the project compiles. The project that cannot format, however, can only have a single module without the language server incorrectly reporting "Unbound module" errors. I've updated the example project listed above to include the other module.

`dune build` runs just fine, but the language server thinks the `Formula` module opened in `Sat` is unbound. I've tried obliterating my switches and reinstalling/updating everything to the latest versions, and still the issue persists. I'll update this thread if I find any other issues or a solution!

**Comment by rgrinberg** [comment] 2021-04-01 07:43
Does it work when you run`$ dune build @fmt --auto-promote`?

**Comment by FinleyMcIlwaine** [comment] 2021-04-01 07:57
> Does it work when you run`$ dune build @fmt --auto-promote`?

Yes it does, that is how I've been formatting instead.

**Comment by FinleyMcIlwaine** [comment] 2021-04-01 21:35
After all this time… I’m ashamed to admit that this issue appears to have been because the path to my project had a `= `character in it. As soon as I remove that character and change the path name, everything works great.

I know I’ve seen some warnings about spaces in path names in the documentation, but I did not know other characters would be invalid as well. I wish it wouldn’t have failed so quietly because of this…

**Comment by mnxn** [comment] 2021-04-01 21:41
Glad you got it working. Sorry it was so hard to find the cause.

I think it should be possible to emit a warning if a project is opened in a problematic path.

**Comment by rgrinberg** [comment] 2021-04-01 21:42
Yeah, this is definitely a bug on our end. I wonder if we're not escaping paths correctly somewhere.

**Comment by rgrinberg** [comment] 2021-04-28 19:46
Fixed in master. Let me know if you encounter other problems like this.

**Closed by rgrinberg** 2021-04-28 19:46 UTC
