### ISSUE TITLE
Adjust lint delay

### ISSUE THREAD

**Issue by modlfo** [ocaml/ocaml-lsp#156] opened 2020-04-18 06:42 UTC
Hi,

Is there a way to delay the lint (error highlighting) when editing code? 

I have a project that is quite large and as I'm typing I can see that the errors are being displayed. I haven't finish the word and the error highlighting is showing. Once I finish typing, the editor hangs for a few seconds until all the lint requests are finished.

It would be nice if I can set a longer delay for this project because sometimes it gets very difficult to write the code.

**Comment by giltho** [comment] 2020-04-21 13:31
The best fix for this is the batching of client requests.
So, although it's not exactly a duplicate, I'm gonna mark it as a duplicate of #116 and close this issue

**Closed by giltho** 2020-04-21 13:31 UTC
