### ISSUE TITLE
Duplicate errors from lsp and dune

### ISSUE THREAD

**Issue by copy** [ocaml/ocaml-lsp#1101] opened 2023-05-23 09:51 UTC
Under some circumstances, ocaml-lsp reports the same error twice, one coming from merlin and one from dune. It happens when type paths don't match exactly, for example (note `Std.Buffer.t` vs `Buffer.t`):

![Screenshot_2023-05-23_17-45-31](https://github.com/ocaml/ocaml-lsp/assets/1816456/11248dfb-337f-4905-acd8-57e71f83f1c7)

**Comment by rgrinberg** [comment] 2023-05-23 19:16
Yup this is a duplicate of #704. I'm not sure what can be done about it.

**Closed by rgrinberg** 2023-05-23 19:16 UTC
