### ISSUE TITLE
Important features no longer work on Windows

### ISSUE THREAD

**Issue by mnxn** [ocaml/ocaml-lsp#184] opened 2020-05-18 05:39 UTC
I recently updated ocaml-lsp to the latest version and immediately I noticed that important features weren't working on Windows:

- The language server does not see external modules and marks each reference to such module as an error. 

- Formatting .ml and .mli files does nothing with no errors.

The VS Code extension has the following errors in `main.ml` even though it builds and runs fine from the terminal.

> Unbound module Stdio
> Hint: Did you mean Stdlib?

> Unbound module My_lib

I use OCaml for Windows installed from here: https://fdopen.github.io/opam-repository-mingw/installation/

I've tried this on a clean install with only ocaml-lsp and ocamlformat installed.

The VS Code output pane does not have any useful information, it only has `time elapsed processing message`. The VS Code developer tools console also has no information.

Before this, I was running a version of ocaml-lsp that was built a few weeks ago, which was running with no problems.

**Comment by giltho** [comment] 2020-05-18 10:13
Hey @mnxn, what version of ocaml are you using ?
Also, do you have the commit hash of the previous version that you were using that worked ? It would be helpful to find the breaking commit

**Comment by mnxn** [comment] 2020-05-18 16:04
I am using OCaml 4.10.0. I unfortunately do not know exactly which version was working before. I will investigate today and try to find which update broke it.

**Comment by rgrinberg** [comment] 2020-05-18 16:57
@mnxn how are you launching the LSP server via vscode? Are you using the global toolchain or some sandbox?

**Comment by mnxn** [comment] 2020-05-18 16:59
I tried both global toolchain and opam sandbox and the behavior is the same.

**Comment by rgrinberg** [comment] 2020-05-18 17:12
Is the server responsive at all? Are you able to get any auto completion for example?

**Comment by mnxn** [comment] 2020-05-18 17:57
Auto completion and types on hover are functional.

**Comment by mnxn** [comment] 2020-05-18 18:57
I went through some of the commits and collected the following data (sorted from oldest to newest):

| Commit Hash | External Modules Work? | Formatting Works? | 
| - | - | - |
| 6f54399a99bbc7c0eb455a568ec723529877708f | Yes | Yes |
| e1073ef2da58af8e09c4c3a46f3f120a58fae355 | Yes | Yes |
| 4a03e80530712e027871529ff4d7fdb38a544202 | No | No |
| 319f4f73530fa3f95987d893473f5057266649e0 | No | No |

The culprit seems to be https://github.com/ocaml/ocaml-lsp/commit/4a03e80530712e027871529ff4d7fdb38a544202

**Comment by rgrinberg** [comment] 2020-05-18 19:18
I'll revert the URI change for now then. We'll try to approach it in a more careful manner and figure out why windows isn't working and why our test suite didn't catch it.

**Comment by giltho** [comment] 2020-05-18 22:50
I was concerned about windows but I made the change, but this is extremely surprising given that I basically copied the typescript implementation written by the microsoft team...
One thing might be the case of the drive letter 🤔

**Comment by giltho** [comment] 2020-05-18 22:51
I'll close this issue when windows + correct URIs work correctly together

**Comment by giltho** [comment] 2020-07-15 21:52
Hi @mnxn, whenever you have time, since you have a windows machine, could you help me with this ?
I just need to know what kind of URI vscode and the server are exchanging on windows :
- In your VSCode JSON setting file, add `"ocaml.trace.server": "verbose"`
- Play with any ocaml file in vscode
- in output > OCaml Language Server, copy paste everything and put it into a file called "whatever.log" so that I can upload it on the [lsp inspector](https://microsoft.github.io/language-server-protocol/inspector/)

If you could do that with both the current version and commit 4a03e80 where we had supposedly better URI handling it would be absolutely amazing

If you don't have time no worry, I'll ask someone else :)

**Comment by mnxn** [comment] 2020-07-15 22:13
Here are the two log files.

[master.log](https://github.com/ocaml/ocaml-lsp/files/4928216/master.log)
[4a03e80.log](https://github.com/ocaml/ocaml-lsp/files/4928217/4a03e80.log)


The immediate issue that stands out to me is that the broken version at 4a03e80 receives path from the server that start with `file:///c:/`, whereas the working version always receives paths that are URL encoded to `file:///c%3A/`.

I think this is because `String.replace_all ~pattern:":" ~with_:"%3A"` was removed in that commit:
https://github.com/ocaml/ocaml-lsp/commit/4a03e80530712e027871529ff4d7fdb38a544202#diff-56d5984b5ab398105d3ccfcbd99ea2e0L45

**Comment by giltho** [comment] 2020-07-15 23:00
hmmm this is frustrating. [The documentation says](https://github.com/mirage/ocaml-uri/blob/master/lib/uri.mli#L62) that `Uri.to_string` is supposed to percent-encode the URI.
However, when I'm testing it, it doesn't seem to be replacing the `:` with it's percent-encoding
I'm missing something here but it's late I'll take a look tomorrow

**Comment by tottenhamjm** [comment] 2020-08-29 14:44
I'm a little late to this, but after going through [the source code](https://github.com/mirage/ocaml-uri/blob/master/lib/uri.ml#L198 I found that both `:` and `@` can be added to the `safe_chars` array which are not encoded. 

It looks like when the `encode` function is matching the `safe_chars_for_component`,  it's matching either `safe_chars_for_path` or `safe_chars_for_query`, both of which include `:` as a safe char. I'll take a deeper look today into it.

**Comment by db4** [comment] 2020-10-14 07:13
> I'll take a look tomorrow

> I'll take a deeper look today into it.

@giltho @johnhaley81 is there any news on this? The issue is quite annoying,  I have to use 5 months old version (https://github.com/ocaml/ocaml-lsp/commit/e1073ef2da58af8e09c4c3a46f3f120a58fae355) on Windows...

**Comment by mnxn** [comment] 2020-10-14 07:24
>  The issue is quite annoying, I have to use 5 months old version ([e1073ef](https://github.com/ocaml/ocaml-lsp/commit/e1073ef2da58af8e09c4c3a46f3f120a58fae355)) on Windows...

Why are you using a 5 month old version? The commit was reverted. I've been using the master version on windows with no problems.

Are you sure you're not encountering some other problem?

**Comment by db4** [comment] 2020-10-14 08:18
Just tried the most recent OCaml Platform/OCaml LSP - indeed, they work on Windows. Almost.  `ocaml.switch-impl-intf` command doesn't:
```
[Trace - 11:12:48 AM] Sending request 'textDocument/documentSymbol - (68)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Work/OCaml/ocaml-vscode/foo.mli"
    }
}


[Trace - 11:12:48 AM] Received response 'textDocument/documentSymbol - (68)' in 2ms.
Result: [
    {
        "name": "bar",
        "detail": "int",
        "kind": 12,
        "deprecated": false,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 13
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 13
            }
        },
        "children": []
    }
]


[Trace - 11:12:52 AM] Sending request 'ocamllsp/switchImplIntf - (69)'.
Params: "file:///c:/Work/OCaml/ocaml-vscode/foo.mli"


[Trace - 11:12:52 AM] Received response 'ocamllsp/switchImplIntf - (69)' in 3ms. Request failed: Failure("provided file URI (param) doesn't follow URI spec") (-32603).
```

**Comment by ulugbekna** [comment] 2020-10-14 08:27
My poor familiarity with windows -- l will send a fix. I wish we used ocaml-uri though

**Comment by rgrinberg** [comment] 2023-05-30 12:56
Long since fixed. Please re-open if there any issues.

**Closed by rgrinberg** 2023-05-30 12:56 UTC
Labels: bug
