### ISSUE TITLE
Can't build when installing with esy

### ISSUE THREAD

**Issue by ulrikstrid** [ocaml/ocaml-lsp#218] opened 2020-07-05 09:45 UTC
This commit https://github.com/ocaml/ocaml-lsp/commit/b4e8c47cdb98e1d59b40baad4721c50017c8c5ae and everything after is broken when installing in a esy project.

cc @prometheansacrifice

**Comment by ulugbekna** [comment] 2020-07-05 15:12
Duplicate of #212. 

May be worth keeping the issue open until Esy solves this problem (if it is indeed Esy problem).

**Comment by EduardoRFS** [comment] 2020-07-05 19:50
It's not an esy problem, if you do a fresh opam install the same problem will arises, it uses (vendored_dir vendor) but that works only if the packages are using dune, as uutf is not using dune anymore, this problem happens

![image](https://user-images.githubusercontent.com/3393115/86541002-90876c00-bedf-11ea-8d2c-6993b968e460.png)

**Comment by prometheansacrifice** [comment] 2020-07-06 13:59
I believe this can be closed now since the fix has landed https://github.com/ocaml/ocaml-lsp/commit/812a18275e0f6ad695092b5eb32f5261adb97005 and tests fine locally

**Closed** 2020-07-06 14:36 UTC
