### ISSUE TITLE
I/O error with files in a subdirectory

### ISSUE THREAD

**Issue by grayswandyr** [ocaml/ocaml-lsp#275] opened 2020-10-26 16:02 UTC
Hi,
first: thanks for your efforts in improving the OCaml developer experience.

I'm using Codium (a variant of VS Code without MS' telemetry). The structure of my (private) project features an `src/` dir as well as an `src/test/` subdir (with ppx_expect tests only). There is a `dune` file in `src/` with, in particular, the `(include_subdirs unqualified)` instruction. In the auto-generated `src/.merlin`, I have `S .` and `S test`. 

However, Codium shows an error message in the "Problems" pane, issued by ocaml-lsp, for every file lying in `src/test`:
```
I/O error: test_foo.ml: No such file or directory
ocamllsp [2, 1]
```
However, `dune` builds and runs tests without any issue.

Also, if `test_foo.ml` is moved to `src`, Codium/ocaml-lsp shows no more error. 

So it's fortunately not a show-stopper but I guess it may indicate a problem to be solved.

**Comment by frejsoya** [comment] 2021-02-02 07:45
I can replicate this with a somewhat minimal example. Not related to `include_subdirs` it triggers seemingly depending on levels of dir path, ie path is stripped somewhere. This is only for ppx_expect tests, ppx_inline_test works fine.

```
I/O error: example_a.ml: No such file or
directory
```

This is only shows in vscode/lsp. dune works fine.

For below project
-  ppx_expect test is ok in `./lspbug/lib/`
-  ppx_expect test is fails in viscose with "" in `./lspbug/lib/a/`
-  ppx_inline tests work in all cases.

```
├── dune-project
└── lspbug
    └── lib
        ├── a
        │   ├── dune
        │   └── example_a.ml
        ├── dune
        └── example.ml
```

I'm not able to run ocamllsp with logging output.

**Comment by frejsoya** [comment] 2021-02-02 07:59
This seems to an unresolved issue with merlin: https://github.com/ocaml/merlin/issues/1095

**Comment by frejsoya** [comment] 2021-02-02 10:33
Maybe I messed up in previous example, please ignore: The following does not work using ppx_expect
```
├── a
│   ├── dune
│   └── example_a.ml
└── dune-project
```

**Comment by frejsoya** [comment] 2021-02-03 10:07
This is the logging output from vscode<->ocamllsp after restart.
```
[Trace - 11:03:51 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 60521,
    "clientInfo": {
        "name": "vscode",
        "version": "1.52.1"
    },
    "rootPath": "/Users/frej/Projects/test",
    "rootUri": "file:///Users/frej/Projects/test",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                }
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    }
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "workDoneProgress": true
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///Users/frej/Projects/test",
            "name": "test"
        }
    ]
}


[Trace - 11:03:51 AM] Received response 'initialize - (0)' in 32ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 2,
            "willSave": false,
            "willSaveWaitUntil": false
        },
        "completionProvider": {
            "triggerCharacters": [
                ".",
                "#"
            ],
            "resolveProvider": true
        },
        "hoverProvider": true,
        "signatureHelpProvider": {
            "triggerCharacters": [
                " ",
                "~",
                "?",
                ":",
                "("
            ]
        },
        "declarationProvider": true,
        "definitionProvider": true,
        "typeDefinitionProvider": true,
        "referencesProvider": true,
        "documentHighlightProvider": true,
        "documentSymbolProvider": true,
        "codeActionProvider": {
            "codeActionKinds": [
                "destruct",
                "inferred_intf"
            ]
        },
        "codeLensProvider": {
            "resolveProvider": false
        },
        "documentFormattingProvider": true,
        "renameProvider": {
            "prepareProvider": true
        },
        "foldingRangeProvider": true,
        "selectionRangeProvider": true,
        "experimental": {
            "ocamllsp": {
                "interfaceSpecificLangId": true,
                "handleSwitchImplIntf": true,
                "handleInferIntf": true
            }
        }
    },
    "serverInfo": {
        "name": "ocamllsp",
        "version": "1.4.0"
    }
}


[Trace - 11:03:51 AM] Sending notification 'initialized'.
Params: {}


[Trace - 11:03:51 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/frej/Projects/test/example_root.ml",
        "languageId": "ocaml",
        "version": 3,
        "text": "\nlet a  = 1\n\nlet%expect_test _ = print_endline \"foo\"\n"
    }
}


[Trace - 11:03:51 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/frej/Projects/test/a/example_a.ml",
        "languageId": "ocaml",
        "version": 2,
        "text": "let a  = 2\n\nlet _ = print_endline \"Formatted\\n\"\nlet%expect_test _ = print_endline \"foo\"\n"
    }
}


[Trace - 11:03:51 AM] Sending request 'textDocument/documentSymbol - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/frej/Projects/test/a/example_a.ml"
    }
}


[Trace - 11:03:51 AM] Sending request 'textDocument/codeAction - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/frej/Projects/test/a/example_a.ml"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 5
        },
        "end": {
            "line": 0,
            "character": 5
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 11:03:51 AM] Received response 'textDocument/documentSymbol - (1)' in 37ms.
Result: []


[Trace - 11:03:51 AM] Received response 'textDocument/codeAction - (2)' in 36ms.
No result returned.


[Trace - 11:03:52 AM] Sending request 'textDocument/foldingRange - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/frej/Projects/test/a/example_a.ml"
    }
}


[Trace - 11:03:52 AM] Received response 'textDocument/foldingRange - (3)' in 0ms.
Result: []


[Trace - 11:03:52 AM] Sending request 'textDocument/codeLens - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/frej/Projects/test/a/example_a.ml"
    }
}


[Trace - 11:03:52 AM] Received response 'textDocument/codeLens - (4)' in 1ms.
Result: []


[Trace - 11:03:52 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/frej/Projects/test/example_root.ml",
    "diagnostics": []
}


[Trace - 11:03:52 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/frej/Projects/test/a/example_a.ml",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 1,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 0
                }
            },
            "severity": 1,
            "source": "ocamllsp",
            "message": "I/O error: example_a.ml: No such file or\ndirectory"
        }
    ]
}


[Trace - 11:03:52 AM] Sending request 'textDocument/codeAction - (5)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/frej/Projects/test/a/example_a.ml"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 5
        },
        "end": {
            "line": 0,
            "character": 5
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 11:03:52 AM] Received response 'textDocument/codeAction - (5)' in 1ms.
No result returned.
```

**Comment by frejsoya** [comment] 2021-02-03 14:50
Alternatively. 

Simply open this project (ocaml-lsp) with vscode and ocaml-platform extension and open a file that uses with ppx_expect. Ie. `fiber-unix/test/barrier_test.ml`

**Comment by ryanslade** [comment] 2021-02-19 07:00
I'm seeing this too and it appears to be a relatively new regression since it only started happening recently, my underlying project code hasn't changed.

**Comment by wokalski** [comment] 2021-11-17 20:53
Any news/workaround for this issue?

**Comment by rgrinberg** [comment] 2021-11-19 05:15
Can this bug still be reproduced in master?

**Comment by wokalski** [comment] 2021-12-21 22:46
This seems to be fixed in master.

**Closed** 2023-01-14 16:35 UTC
